# Generated by Django 3.2.9 on 2022-05-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250, verbose_name='Название')),
                ('location', models.CharField(max_length=500, verbose_name='Местоположение')),
                ('bassin_area', models.CharField(max_length=500, verbose_name='Бассейновый округ')),
                ('river_bassin', models.CharField(max_length=500, verbose_name='Речной бассейн')),
                ('area', models.FloatField(verbose_name='Площадь')),
            ],
            options={
                'verbose_name': 'Озеро',
                'verbose_name_plural': 'Озера',
            },
        ),
    ]
